# Generated by Django 6.0.5 on 2026-05-29 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_producto', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=250)),
                ('precio', models.IntegerField()),
            ],
        ),
    ]
